Add Material3 Theme
BottleRocketStudios/Kmp-demo pull request #15
Opened 2023-11-19 22:49 UTC by VanyaHuamanBottleRocket

2023-11-20 15:40 UTC, BottleRocket-Colin requested changes
We can use a composable factory function to generate our Typography.  Also can probably remove platform expect/ actual.

2023-11-20 15:40 UTC, BottleRocket-Colin commented on androidApp/src/androidMain/kotlin/com/br/kmmdemo/android/MainActivity.kt
> +            MainView(platform.screenSize())
Since this code is already platform specific (in the Android app module) do we need to abstract logic via platform file?

2023-11-20 15:40 UTC, BottleRocket-Colin commented on shared/src/commonMain/kotlin/com/br/kmmdemo/theme/Typography.kt
> +val kmpTypography = Typography(
Change this to a factory function that is a composable. Looking at theme code that uses this val it is used from within a composable.  So it should work out.

2023-11-20 15:40 UTC, BottleRocket-Colin commented on shared/src/iosMain/kotlin/com/br/kmmdemo/Platform.ios.kt
> +
Same comment here as above.  We can probably just call this platform logic directly where it's used as that would already be platform specific code.

2023-11-21 14:03 UTC, br-Emery approved these changes

2023-11-21 16:34 UTC, BottleRocket-Colin approved these changes

2023-11-21 16:37 UTC, merged