[ASAA-178] Connecting API Calls to UI
BottleRocketStudios/Kmp-demo pull request #35
Opened 2024-02-29 21:27 UTC by MMurrayAtBR

### [[ASAA-178] Connecting API Calls to UI](https://bottlerocketstudios.atlassian.net/browse/ASAA-178)

- Added repositoryModule to appModule
- Added missing value to DailyDataPointValuesDto
- Updated DailyForecastChip to display precipitation percentage only if the percentage is over 0
- Add `= null` to data class values where necessary
- Updated ForecastState with additional fields needed for UI elements
- Updated HomeBottomSheet to display error text field if forecasts are missing
- Updated HomeCurrentWeather to display API data correctly
- Updated HomeState (and converter) with values needed for WeatherDetails widgets
- Moved multiple files from Domain module to Data module
- Updated multiple Composable functions to check nullable values
- Updated Preview functions and MockData with new data types
- Updated ktorClient to match Ignite
- Updated NetworkRoutes with URLs and constants
- Updated TomorrowIoService with calls to get daily, hourly, and real time forecasts
- Updated UVIndexEnum and WindDirection with functions to get correct enum value
- Updated WeatherDetails for nullable values
- Removed WeatherDetailsState because it is no longer needed
- Added API calls to WeatherRepository and WeatherRepoImplementation
- Added ApiException class
- Created HomeViewModelUtils to hold all of the utility functions for HomeViewModel
- Added Domain classes, DTO classes, and converters for RealTime forecasts
- Removed TomorrowService interface on advice from Colin

<img src="https://github.com/BottleRocketStudios/Kmp-demo/assets/108824364/4e67d100-ac89-4170-aaa3-2d2ac40ec90e" width=200>
<img src="https://github.com/BottleRocketStudios/Kmp-demo/assets/108824364/b8af721e-1d97-4a55-ad32-5d2f3a80a133" width=200>
<img src="https://github.com/BottleRocketStudios/Kmp-demo/assets/108824364/7273e686-2487-4eb9-804a-7ce33f213740" width=200>
<img src="https://github.com/BottleRocketStudios/Kmp-demo/assets/108824364/8c6fb101-a271-4bb5-83a0-81808fb113f9" width=200>
<img src="https://github.com/BottleRocketStudios/Kmp-demo/assets/108824364/b1f4c1eb-851b-45e3-8d39-30c7387f8c84" width=200>
<img src="https://github.com/BottleRocketStudios/Kmp-demo/assets/108824364/9bf39d87-6ed1-45e9-860e-901d17f36d70" width=200>

2024-03-01 22:01 UTC, VanyaHuamanBottleRocket approved these changes

2024-03-01 22:01 UTC, VanyaHuamanBottleRocket commented on compose/src/commonMain/kotlin/com/br/kmpdemo/compose/ui/forecasts/DailyForecastChip.kt
> +                    stringResource(SharedRes.strings.input_percentage, precipProbability ?: "--"),
could make "--" into a const

2024-03-01 22:01 UTC, VanyaHuamanBottleRocket commented on compose/src/commonMain/kotlin/com/br/kmpdemo/compose/ui/forecasts/HourlyForecastChip.kt
> +                    stringResource(SharedRes.strings.input_percentage, precipProbability ?: "0.0"),
could make "0.0" into a const

2024-03-04 15:50 UTC, BottleRocket-Colin requested changes
really awesome PR.  Some minor changes to compress code.

2024-03-04 15:50 UTC, BottleRocket-Colin commented on compose/src/commonMain/kotlin/com/br/kmpdemo/compose/ui/weatherDetails/uvIndex/UVIndexEnum.kt
> +    when (this ?: -1.0) {
or use Double.MIN

2024-03-04 15:50 UTC, BottleRocket-Colin commented on compose/src/commonMain/kotlin/com/br/kmpdemo/compose/ui/weatherDetails/wind/WindDirectionEnum.kt
> +enum class WindDirectionEnum(val direction: String, val degrees: Double) {
Good idea Vanya.  the direction could be the type of the reference to the string,

2024-03-04 15:50 UTC, BottleRocket-Colin commented on compose/src/commonMain/kotlin/com/br/kmpdemo/compose/ui/weatherDetails/wind/WindDirectionEnum.kt
> +    return when (this ?: -1.0) {
Same comment as before:  -1.0 could be Double.MIN

2024-03-04 15:50 UTC, BottleRocket-Colin commented on data/src/commonMain/kotlin/com/br/kmpdemo/converters/RealTimeDataDtoToRealTimeDataConverter.kt
> +    return RealTimeData(
Could expression function

2024-03-04 15:50 UTC, BottleRocket-Colin commented on data/src/commonMain/kotlin/com/br/kmpdemo/converters/RealTimeDtoToRealTimeConverter.kt
> +fun RealTimeDto?.toRealTimeModel(): RealTime {
expression function

2024-03-04 15:50 UTC, BottleRocket-Colin commented on data/src/commonMain/kotlin/com/br/kmpdemo/network/KtorClient.kt
> +//            }
Go ahead and delete this commented code.  Header for sure.

2024-03-04 15:50 UTC, BottleRocket-Colin commented on data/src/commonMain/kotlin/com/br/kmpdemo/network/service/TomorrowIoService.kt
> +                url(NetworkRoutes.getDailyForecast(location, units))
Let's have a chat.  We may be able to make this more KTOR idiomatic

2024-03-04 15:50 UTC, BottleRocket-Colin commented on shared/src/commonMain/kotlin/com/br/kmpdemo/viewmodels/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.Lazily, null)
Could either create an extension function for the stateIn call, or handle default state in the converter function.

2024-03-04 15:50 UTC, BottleRocket-Colin commented on shared/src/commonMain/kotlin/com/br/kmpdemo/viewmodels/HomeViewModelUtils.kt
> +        return this.toReformattedDate() == today
Some small tinkers here could make this an expression.

2024-03-05 23:30 UTC, merged